#pragma once

enum operationType
{
	OPERATION_TYPE_NONE = 0,
	OPERATION_TYPE_BIOPSY,
	OPERATION_TYPE_CRYOTHERAPY,
	OPERARION_TYPE_BRACHYTHERAPY,
	OPERATION_TYPE_OZONETHERAPY,
	OPERATION_TYPE_TPS,
	OPERATION_TYPE_REVIEW
};

enum WIZARD_STEP {
	WSTEP_CAM = 1, //启动界面
	WSTEP_MRI,     //MRI启动界面
	WSTEP_PAT,     //病人
	WSTEP_BAS,     //选择base
	WSTEP_CAL,	    //标定
	WSTEP_END      //结束
};

enum WIZARD_STEP_RESULT {
	WSRET_OK = 0,
	WSRET_ERR
};

enum DEVICETYPE
{
	DEVICE_CT = 0,
    DEVICE_MRI,
	DEVICE_US
};

enum NAVIGATIONMODE
{
	NAVIGATION_ONLINE_MRI = 0,
	NAVIGATION_OFFLINE,
	NAVIGATION_OFFLINE_MRI
};

enum TRACK_DEVICE_TYPE
{
	TRACK_DEVICE_NDI_OPTIC = 1,
	TRACK_DEVICE_NDI_EM,
	TRACK_DEVICE_VIRTUAL,
	TRACK_DEVICE_MICRONTRACKER
};

enum RESP_FILTER_TYPE
{
	FILTER_IIR_BANDPASS = 0,
	FILTER_FIR_BANDPASS,
	FILTER_FIR_LOWPASS
};